---
title: "R Notebook"
output: html_notebook
---

## Setting up the environment and displaying session information for reproducibility
```{r}
library(Seurat, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(doParallel, quietly = TRUE)
source_path = 'C:\\Users\\15177\\OneDrive - Michigan State University\\Documents\\Projects\\Prj161-snSeq-Mm_TCDD_DR_Sept2019\\snSeq-DGE\\R\\simulation_functions.R'
source('../R/dose_response_models.R') #TODO: CHANGE TO RELATIVE PATH
source(source_path)
sessionInfo()
memory.limit(size = 64000)
```

```{r}
plotDataSummary = function(realData){
  P1 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean, y = percent_zero, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('') +
    theme_classic()
  
  P2 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean_real, y = percent_zero, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('') +
    theme_classic()
  
  P3 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean, y = mean_real, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('Correlation of estimated mean and mean expression') +
    theme_classic()
  
  
  P4 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = percent_zero, y = var_real, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('') +
    theme_classic()
  
  P5 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean_real, y = var_real, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('') +
    theme_classic()
  
  P6 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean, y = sd, colour = factor(meta_var))) +
    geom_point() +
    ggtitle('') +
    theme_classic()
  
  figure = ggpubr::ggarrange(P1, P2, P3, P4, P5, P6, labels = c("A", "B", "C", "D", "E", "F"), ncol = 3, nrow = 2)
  figure
}
```


```{r fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust1.RData')

c1 = rbind(
  realParams(import, 6, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c1)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust2.RData')

c2 = rbind(
  realParams(import, 6, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c2)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust3.RData')

c3 = rbind(
  realParams(import, 6, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c3)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust4.RData')

c4 = rbind(
  realParams(import, 6, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c4)
```


```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust5.RData')

c5 = rbind(
  realParams(import, 6, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 6, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c5)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust6.RData')

c6 = rbind(
  realParams(import, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c6)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust7.RData')

c7 = rbind(
  realParams(import, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c7)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust8.RData')

c8 = rbind(
  realParams(import, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c8)
```

```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust9.RData')

c9 = rbind(
  realParams(import, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c9)
```


```{r echo = FALSE, fig.width = 20, fig.height = 8}
import = importSeu('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust10.RData')

c10 = rbind(
  realParams(import, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(import, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)

plotDataSummary(c10)
```

Combine outputs and export for subsequent analyses
```{r}
c1$Cells = 1
c2$Cells = 2
c3$Cells = 3
c4$Cells = 4
c5$Cells = 5
c6$Cells = 6
c7$Cells = 7
c8$Cells = 8
c9$Cells = 9
c10$Cells = 10

C = rbind(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10)
saveRDS(C, file = 'EstimatedParameters.RData')
```

